language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - echo ${TRAVIS_COMMIT}
  - echo ${TRAVIS_TAG}
  - echo ${TRAVIS_BRANCH}
  - echo ${TRAVIS_BUILD_NUMBER}
  - echo ${TRAVIS_REPO_SLUG}
  - ./_build.sh
  - ./_deploy.sh
