name: Build and Deploy bookdown

on:
  push:
    branches:
      - main
      - master


jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: brew install pandoc

      - name: Cache renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install R dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Build site and downloads
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'
          touch _book/.nojekyll

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
